version: '3'
services:
  db:
    image: mysql:8.0
    container_name: ailens_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ailens@123
      MYSQL_DATABASE: ailens
      MYSQL_USER: ailens
      MYSQL_PASSWORD: Ailens@123
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-pAilens@123", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
    dns:
      - 8.8.8.8
      - 8.8.4.4
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ailens_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:6000"
    restart: always
    volumes:
      - .:/ailensfashion
    ports:
      - "6000:6000"
    env_file:
      - ailensfashion/.env
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4

  website:
    build: 
      context: ./ailens-fashion
      dockerfile: Dockerfile.nextjs
    container_name: ailens_website
    restart: always
    volumes:
      - ./website:/ailensfashion/ailens-fashion
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  memcached:
    build:
      context: .
      dockerfile: Dockerfile.memcached
    container_name: ailens_cache
    restart: always
    ports:
      - "11211:11211"
volumes:
  data: